import type { Agent, AgentResult, AgentStatus, Task } from '../interfaces';

export class CoderAgent implements Agent {
  id = 'coder';
  name = 'Coder Agent';
  description = 'Writes and modifies code across multiple files';
  type = 'code' as const;
  private _status: AgentStatus = 'idle';

  async execute(task: Task): Promise<AgentResult> {
    this._status = 'running';
    try {
      const files = task.files?.map((f) => ({
        path: f,
        content: `// Generated by CoderAgent for task: ${task.id}\n// ${task.title}\n\n`,
        action: 'modify' as const,
      })) || [];

      this._status = 'idle';
      return {
        success: true,
        output: `Implemented ${files.length} file(s) for: ${task.title}`,
        files,
        summary: `Modified ${files.length} file(s)`,
      };
    } catch (error) {
      this._status = 'error';
      return { success: false, output: '', error: String(error) };
    }
  }

  async cancel(): Promise<void> {
    this._status = 'idle';
  }

  status(): AgentStatus {
    return this._status;
  }
}
